"""add_telegram_binding

Revision ID: a2e649dd8363
Revises: 412f954fecd1
Create Date: 2025-12-29 02:35:05.551307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e649dd8363'
down_revision: Union[str, Sequence[str], None] = '412f954fecd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply_message_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_message_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reply_message_lookup', 'reply_message_bindings', ['platform', 'external_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reply_message_lookup', table_name='reply_message_bindings')
    op.drop_table('reply_message_bindings')
    # ### end Alembic commands ###
